services:
  nginx:
    image: nginx:1.26.0-bookworm
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/conf:/etc/nginx/ssl:ro
      - ./certbot/www:/var/www/certbot:ro
    networks:
      - dc_net

  postgres:
    env_file: postgres.env
    image: postgres:15-alpine
    expose:
      - 5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - dc_net

  certbot:
    image: certbot/certbot:v2.10.0
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
    networks:
      - dc_net

  llm-chat-web:
    env_file: llm_chat/.env
    image: llm-chat
    networks:
      - dc_net
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  dc_net:
    driver: bridge
    attachable: true